export default {
    FREDOKA_BOLD: 'Fredoka-Bold',
    FREDOKA_LIGHT: 'Fredoka-Light',
    FREDOKA_MEDIUM: 'Fredoka-Medium',
    FREDOKA_REGULAR: 'Fredoka-Regular',
    FREDOKA_SEMIBOLD: 'Fredoka-SemiBold',
    FREDOKAONE_REGULAR: 'FredokaOne-Regular',
    POPPINS_BOLDITALIC: 'Poppins-BoldItalic',
    POPPINS_LIGHT : 'Poppins-Light',
    POPPINS_MEDIUM : 'Poppins-Medium',
    POPPINS_REGULAR : 'Poppins-Regular',
    POPPINS_BOLD : 'Poppins-Bold',
    POPPINS_SEMIBOLD : 'Poppins-SemiBold',
    POPPINS_SEMIBOLDITALIC: 'Poppins-SemiBoldItalic',
    FREDOKA_CONDENSED_SEMIBOLD: 'Fredoka_Condensed-SemiBold',
    NOTO_REGULAR: 'NotoSerif-Regular',
    OPENSANS_REGULAR: 'OpenSans-Regular',
};